/* eslint-disable jsx-a11y/role-supports-aria-props -- interactive calendar cells retain grid semantics */
type DailyPoint = { dateKey: string; completed: boolean; scheduled: boolean };
type WeeklyDay = { dateKey: string; completed: boolean };
export type DailyGridCell = { dateKey: string; point?: DailyPoint; column: number; row: number };
export type TaskHistory = { daily?: { startDate: string; endDate: string; points: DailyPoint[] }; weekly?: { weekStart: string; weekEnd: string; completed: number; target: number; days: WeeklyDay[] } };
const dayLabels = ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"];
function parseDateKey(dateKey: string) { const [year, month, day] = dateKey.split("-").map(Number); return new Date(Date.UTC(year, month - 1, day)); }
function dateKeyFromDate(date: Date) { return date.toISOString().slice(0, 10); }
function addDays(date: Date, days: number) { const result = new Date(date); result.setUTCDate(result.getUTCDate() + days); return result; }
export function buildDailyCalendarGrid(points: DailyPoint[], weeks = 12): DailyGridCell[] { const lastPoint = points[points.length - 1]; if (!lastPoint || weeks < 1) return []; const lastDate = parseDateKey(lastPoint.dateKey); const lastSunday = addDays(lastDate, -lastDate.getUTCDay()); const firstSunday = addDays(lastSunday, -(weeks - 1) * 7); const pointsByDate = new Map(points.map((point) => [point.dateKey, point])); return Array.from({ length: weeks * 7 }, (_, index) => { const column = Math.floor(index / 7); const row = index % 7; const dateKey = dateKeyFromDate(addDays(firstSunday, column * 7 + row)); return { dateKey, point: pointsByDate.get(dateKey), column, row }; }); }

type CompletionChartProps = { history?: TaskHistory; title: string; frequency: "DAILY" | "WEEKLY"; todayKey: string; startDate?: string; onToggle: (dateKey: string, completed: boolean) => void };
export function CompletionChart({ history, title, frequency, todayKey, startDate, onToggle }: CompletionChartProps) {
  if (frequency === "DAILY" && history?.daily) return <DailyCompletionChart history={history.daily} title={title} todayKey={todayKey} onToggle={onToggle} />;
  if (frequency === "WEEKLY" && history?.weekly) return <WeeklyCompletionChart history={history.weekly} title={title} todayKey={todayKey} startDate={startDate ?? history.weekly.weekStart} onToggle={onToggle} />;
  return null;
}

function DailyCompletionChart({ history, title, todayKey, onToggle }: { history: NonNullable<TaskHistory["daily"]>; title: string; todayKey: string; onToggle: (dateKey: string, completed: boolean) => void }) {
  const cells = buildDailyCalendarGrid(history.points);
  return <section className="completion-chart daily-chart" aria-label={`Historial de ${title}`}><div className="completion-chart-heading"><div><p className="chart-eyebrow">Últimas 12 semanas</p><h3 className="chart-title">Constancia</h3></div><span className="chart-range">{history.startDate} — {history.endDate}</span></div><div className="chart-scroll"><div className="daily-grid-layout"><div className="daily-day-labels" aria-hidden="true">{dayLabels.map((day) => <span key={day}>{day}</span>)}</div><div className="daily-grid" role="grid" aria-label={`Contribuciones de ${title}, semanas de domingo a sábado, de ${history.startDate} a ${history.endDate}`}>{cells.map((cell) => { const point = cell.point; const status = point ? point.completed ? "completada" : point.scheduled ? "programada, pendiente" : "no programada" : "fuera del rango disponible"; const editable = Boolean(point?.scheduled && cell.dateKey <= todayKey); const label = `${cell.dateKey}: ${status}${editable ? ". Pulsar para cambiar el estado" : cell.dateKey > todayKey ? ". Fecha futura" : ""}`; const content = point ? point.completed ? "✓" : point.scheduled ? "•" : "–" : ""; return point && point.scheduled && cell.dateKey <= todayKey ? <button key={cell.dateKey} type="button" className={`daily-cell ${point.completed ? "is-complete" : "is-pending"}`} role="gridcell" aria-label={label} title={label} aria-pressed={point.completed} onClick={() => onToggle(cell.dateKey, point.completed)}>{content}</button> : <span key={cell.dateKey} className={`daily-cell ${point ? point.completed ? "is-complete" : point.scheduled ? "is-pending" : "is-unscheduled" : "is-unavailable"}`} role="gridcell" aria-label={label} title={label}>{content}</span>; })}</div></div></div><div className="chart-legend" aria-label="Leyenda del historial"><span><i className="legend-mark is-complete">✓</i> Completada</span><span><i className="legend-mark is-pending">•</i> Pendiente</span><span><i className="legend-mark is-unscheduled">–</i> No programada</span></div></section>;
}

function WeeklyCompletionChart({ history, title, todayKey, startDate, onToggle }: { history: NonNullable<TaskHistory["weekly"]>; title: string; todayKey: string; startDate: string; onToggle: (dateKey: string, completed: boolean) => void }) {
  return <section className="completion-chart weekly-chart" aria-label={`Progreso semanal de ${title}`}><div className="completion-chart-heading"><div><p className="chart-eyebrow">Semana del {history.weekStart}</p><h3 className="chart-title">Ritmo semanal</h3></div><strong className="weekly-total">{history.completed}<span>/{history.target}</span></strong></div><div className="weekly-bars" role="list" aria-label={`Días de la semana de ${title}`}>{history.days.map((day, index) => { const editable = day.dateKey >= startDate && day.dateKey <= todayKey; const label = `${day.dateKey}: ${day.completed ? "completado" : "pendiente"}${editable ? ". Pulsar para cambiar el estado" : day.dateKey < startDate ? ". Día no disponible antes del inicio" : ". Fecha futura"}`; const bar = <div className={`weekly-bar ${day.completed ? "is-complete" : "is-pending"}`}><span aria-hidden="true">{day.completed ? "✓" : "–"}</span></div>; return <div className="weekly-day" key={`${day.dateKey}-${index}`} role="listitem" aria-label={label} title={label}>{editable ? <button type="button" className="weekly-chart-button" aria-label={label} aria-pressed={day.completed} onClick={() => onToggle(day.dateKey, day.completed)}>{bar}</button> : bar}<span className="weekly-day-label">{day.dateKey.slice(5)}</span></div>; })}</div><p className="chart-caption">{history.completed} de {history.target} repeticiones · termina el {history.weekEnd}</p></section>;
}
