"use client";

import { IconCheck } from "./icons";
import { SubtaskActions } from "./SubtaskActions";
import { SubtaskEditor } from "./SubtaskEditor";
import type { Subtask } from "./types";
import type { CSSProperties } from "react";

type Props = { node: Subtask; level: number; siblingIndex: number; siblingCount: number; busyId: string | null; parentOptions: Subtask[]; onToggle: (node: Subtask, completed: boolean) => void; onAdd: (node: Subtask) => void; onAddSubmit: (node: Subtask, title: string) => Promise<void>; onRename: (node: Subtask, title: string) => Promise<void>; onEdit: (node: Subtask) => void; onCancelEdit: () => void; onCancelAdd: () => void; onDelete: (node: Subtask) => void; onMove: (node: Subtask, direction: "up" | "down") => void; onChangeParent: (node: Subtask, parentId: string | null) => void };
export function TaskTreeNode({ node, level, siblingIndex, siblingCount, busyId, parentOptions, onToggle, onAdd, onAddSubmit, onRename, onEdit, onCancelEdit, onCancelAdd, onDelete, onMove, onChangeParent }: Props) {
  const leaves = getLeaves(node); const completed = leaves.filter((leaf) => leaf.completed).length; const checked = leaves.length > 0 && completed === leaves.length; const mixed = completed > 0 && !checked; const editing = busyId === `edit-${node.id}`; const adding = busyId === `add-${node.id}`; const branchIds = new Set(getBranchNodes(node).map((item) => item.id));
  return <li className="task-tree-node" aria-label={`${node.title}, ${node.children.length ? "rama" : "hoja"}, nivel ${level}`}>
    <div className="task-tree-row" style={{ "--tree-level": Math.min(level, 4) } as CSSProperties}><button type="button" className={`task-tree-toggle ${checked ? "is-checked" : ""}`} aria-label={`${checked ? "Desmarcar" : "Completar"} ${node.title}${node.children.length ? `, ${leaves.length} hojas` : ""}`} aria-pressed={checked} aria-busy={busyId === node.id} onClick={() => onToggle(node, !checked)}><span className={mixed ? "is-mixed" : ""}>{checked ? <IconCheck className="size-3" /> : mixed ? "–" : ""}</span></button><div className="task-tree-title"><span className={checked ? "is-done" : ""}>{node.title}</span><small>{node.children.length ? `Rama · ${completed}/${leaves.length} hojas` : "Hoja"}</small></div><div className="task-tree-controls"><label className="sr-only" htmlFor={`parent-${node.id}`}>Grupo visual de {node.title}</label><select id={`parent-${node.id}`} className="task-tree-parent" aria-label={`Grupo visual de ${node.title}`} value={node.parentId ?? ""} onChange={(event) => onChangeParent(node, event.target.value || null)}><option value="">Sin grupo</option>{parentOptions.filter((parent) => !branchIds.has(parent.id)).map((parent) => <option key={parent.id} value={parent.id}>{parent.title}</option>)}</select><SubtaskActions canMoveUp={siblingIndex > 0} canMoveDown={siblingIndex < siblingCount - 1} onAdd={() => onAdd(node)} onEdit={() => onEdit(node)} onMoveUp={() => onMove(node, "up")} onMoveDown={() => onMove(node, "down")} onDelete={() => onDelete(node)} /></div></div>
    {editing && <SubtaskEditor initialTitle={node.title} label={`Renombrar ${node.title}`} onCancel={onCancelEdit} onSave={(title) => onRename(node, title)} />}{adding && <SubtaskEditor label={`Añadir hijo a ${node.title}`} onCancel={onCancelAdd} onSave={(title) => onAddSubmit(node, title)} />}
    {node.children.length > 0 && <ul className="task-tree-children">{node.children.map((child, index) => <TaskTreeNode key={child.id} node={child} level={level + 1} siblingIndex={index} siblingCount={node.children.length} busyId={busyId} parentOptions={parentOptions} onToggle={onToggle} onAdd={onAdd} onAddSubmit={onAddSubmit} onRename={onRename} onEdit={onEdit} onCancelEdit={onCancelEdit} onCancelAdd={onCancelAdd} onDelete={onDelete} onMove={onMove} onChangeParent={onChangeParent} />)}</ul>}
  </li>;
}
function getLeaves(node: Subtask): Subtask[] { return node.children.length ? node.children.flatMap(getLeaves) : [node]; }
function getBranchNodes(node: Subtask): Subtask[] { return [node, ...node.children.flatMap(getBranchNodes)]; }
